sudo: false
language: fortran
compiler:
  - gfortran
os:
  - linux
addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
    packages:
      - libnetcdf-dev
      - libfftw3-dev
    #   - libfftw3-3
    #   - fftw-dev
      - gfortran
script:
  - uname -n
  - ls /usr/lib/
  - ls /usr/include/
  - locate fftw3.f03
  - sed -i "s|FFTW_PATH=/usr/local|FFTW_PATH=/usr|" makefile
  - sed -i "s|NCDF_PATH = /usr/local|NCDF_PATH = /usr|" makefile
  - make test -j4
  - make -j4
