site_name: ICAR
nav:
- Home: index.md
- Compiling: compiling.md
- Running: running/running.md
- Settings Documentation: running/settings_documentation.md
- Developing: developing.md
- Errors: errors.md
theme: readthedocs
google_analytics: ['UA-108421993-4', 'icar.readthedocs.org']
